### ISSUE TITLE
Bug in EI acquisition expression

### ISSUE THREAD

**Issue by BlindApe** [yanyachen/rBayesianOptimization#10]
As stated 	yonghuajiang, according to (2) formula in the reference paper, 'Practical Bayesian Optimization of Machine Learning Algorithms'

line 28 at Utility.R should be:
Utility <- (GP_Mean - y_max - eps) * pnorm(z) + sqrt(GP_MSE) * **dnorm(z),**   (instead of pnorm(z))

**Comment by yanyachen** [comment]
EI utility function expression fixed. I didn't merge that pull request because it didn't pass checks.
Thank you very much.
