### ISSUE TITLE
kernel = "matern", nu = 5/2 is not working

### ISSUE THREAD

**Issue by pranasblk** [yanyachen/rBayesianOptimization#12]
`> OPT_Res <- BayesianOptimization(Test_Fun,
+                                 bounds = list(x = c(1, 3)),
+                                 init_points = 2, n_iter = 10,
+                                 acq = "ei", kappa = 2.576, eps = 0.0,
+                                 kernel = "matern", nu = 5/2, verbose = TRUE)`

Result:
`Error in corr$type : $ operator is invalid for atomic vectors
In addition: Warning message:
In GPfit::GP_fit(X = Par_Mat[Rounds_Unique, ], Y = Value_Vec[Rounds_Unique],  :
  nug_thres is outside of the normal range of [10, 25].`

or

`> OPT_Res <- BayesianOptimization(Test_Fun,
+                                 bounds = list(x = c(1, 3)),
+                                 init_points = 2, n_iter = 10,
+                                 acq = "ei", kappa = 2.576, eps = 0.0,
+                                 kernel = "matern", verbose = TRUE)`

Result:
`elapsed = 0.00	Round = 1	x = 1.2185	Value = 1.0471 
elapsed = 0.00	Round = 2	x = 2.2607	Value = 1.3450 
Error in corr$type : $ operator is invalid for atomic vectors`

**Comment by yanyachen** [comment]
kernel parameter should be a list that specifies the type of correlation function along with the smoothness parameter. Popular choices are square exponential (default) or matern 5/2.
For example, 
`
kernel = list(type = "matern", nu = 5/2)
`

**Comment by pranasblk** [comment]
Thanks for looking into it - my mistake. 
I've just digged it from the GPfit doc.
