### ISSUE TITLE
Error in -"Round" : invalid argument to unary operator

### ISSUE THREAD

**Issue by dfayzur** [yanyachen/rBayesianOptimization#6]
After running the following example given in the package, I receive "**Error in -"Round" : invalid argument to unary operator**". The operating system is Windows 7, and running R x64 3.3.1 in the system.

_# Example 1: Optimization

Test_Fun <- function(x) {
  list(Score = exp(-(x - 2)^2) + exp(-(x - 6)^2/10) + 1/ (x^2 + 1),
       Pred = 0)
}
OPT_Res <- BayesianOptimization(Test_Fun,
                                bounds = list(x = c(1, 3)),
                                init_points = 2, n_iter = 1,
                                acq = "ucb", kappa = 2.576, eps = 0.0,
                                verbose = TRUE)_

**Comment by dfayzur** [comment]
OK, solved once I updated the data.table library to version 1.9.6
Previously, version 1.9.4 was installed to the computer.
It would be nice to check **_data.table_** version at the time to install **rBayesianOptimization**

**Comment by yanyachen** [comment]
Yes, you are right. I didn't realize the "negative string indices" doesn't work for data.table version 1.9.4. I will leave this issue open until I add the version check to DESCRIPTION. Thank you very much.

**Comment by yanyachen** [comment]
Version check for data.table added
